/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_example_test_jnitest_EncryptUtils */

#ifndef _Included_org_example_test_jnitest_EncryptUtils
#define _Included_org_example_test_jnitest_EncryptUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_example_test_jnitest_EncryptUtils
 * Method:    getKeyFromNative
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_example_test_jnitest_EncryptUtils_getKeyFromNative
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
